exports.up = async function (knex) {
  await knex.schema.createTable('fetal_weekly_content', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    table.integer('week_number').unique().notNullable();
    table.string('title_en', 500);
    table.string('title_am', 500);
    table.string('title_om', 500);
    table.string('title_so', 500);
    table.string('image_url', 500);
    table.string('image_alt_en', 500);
    table.string('image_alt_am', 500);
    table.string('image_alt_om', 500);
    table.string('image_alt_so', 500);
    table.text('summary_en');
    table.text('summary_am');
    table.text('summary_om');
    table.text('summary_so');
    table.decimal('baby_length_cm', 6, 2);
    table.decimal('baby_weight_g', 8, 2);
    table.integer('days_remaining');
    table.integer('heart_rate');
    table.string('size_comparison_en', 500);
    table.string('size_comparison_am', 500);
    table.string('size_comparison_om', 500);
    table.string('size_comparison_so', 500);
    table.text('milestone_en');
    table.text('milestone_am');
    table.text('milestone_om');
    table.text('milestone_so');
    table.text('physical_development_en');
    table.text('physical_development_am');
    table.text('physical_development_om');
    table.text('physical_development_so');
    table.text('brain_dev_en');
    table.text('brain_dev_am');
    table.text('brain_dev_om');
    table.text('brain_dev_so');
    table.text('heart_dev_en');
    table.text('heart_dev_am');
    table.text('heart_dev_om');
    table.text('heart_dev_so');
    table.text('organ_dev_en');
    table.text('organ_dev_am');
    table.text('organ_dev_om');
    table.text('organ_dev_so');
    table.text('bone_muscle_dev_en');
    table.text('bone_muscle_dev_am');
    table.text('bone_muscle_dev_om');
    table.text('bone_muscle_dev_so');
    table.text('movement_en');
    table.text('movement_am');
    table.text('movement_om');
    table.text('movement_so');
    table.jsonb('senses').defaultTo('[]');
    table.text('maternal_changes_en');
    table.text('maternal_changes_am');
    table.text('maternal_changes_om');
    table.text('maternal_changes_so');
    table.text('common_symptoms_en');
    table.text('common_symptoms_am');
    table.text('common_symptoms_om');
    table.text('common_symptoms_so');
    table.text('health_tip_en');
    table.text('health_tip_am');
    table.text('health_tip_om');
    table.text('health_tip_so');
    table.text('antenatal_care_en');
    table.text('antenatal_care_am');
    table.text('antenatal_care_om');
    table.text('antenatal_care_so');
    table.text('screening_information_en');
    table.text('screening_information_am');
    table.text('screening_information_om');
    table.text('screening_information_so');
    table.string('bonding_activity_title_en', 500);
    table.string('bonding_activity_title_am', 500);
    table.string('bonding_activity_title_om', 500);
    table.string('bonding_activity_title_so', 500);
    table.text('bonding_activity_description_en');
    table.text('bonding_activity_description_am');
    table.text('bonding_activity_description_om');
    table.text('bonding_activity_description_so');
    table.text('emotional_message_en');
    table.text('emotional_message_am');
    table.text('emotional_message_om');
    table.text('emotional_message_so');
    table.text('diary_prompt_en');
    table.text('diary_prompt_am');
    table.text('diary_prompt_om');
    table.text('diary_prompt_so');
    table.text('warning_signs_en');
    table.text('warning_signs_am');
    table.text('warning_signs_om');
    table.text('warning_signs_so');
    table.text('when_to_contact_provider_en');
    table.text('when_to_contact_provider_am');
    table.text('when_to_contact_provider_om');
    table.text('when_to_contact_provider_so');
    table.boolean('is_active').defaultTo(true);
    table.uuid('created_by').references('id').inTable('users').onDelete('SET NULL');
    table.uuid('reviewed_by').references('id').inTable('users').onDelete('SET NULL');
    table.timestamp('created_at').defaultTo(knex.fn.now());
    table.timestamp('updated_at').defaultTo(knex.fn.now());
    table.index('week_number');
  });

  await knex.schema.createTable('fetal_development_items', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    table.uuid('week_id').notNullable().references('id').inTable('fetal_weekly_content').onDelete('CASCADE');
    table.string('category', 100);
    table.string('title_en', 500);
    table.string('title_am', 500);
    table.string('title_om', 500);
    table.string('title_so', 500);
    table.integer('display_order').defaultTo(0);
    table.timestamp('created_at').defaultTo(knex.fn.now());
    table.index('week_id');
  });

  await knex.schema.createTable('fetal_checklist_items', (table) => {
    table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
    table.uuid('week_id').notNullable().references('id').inTable('fetal_weekly_content').onDelete('CASCADE');
    table.string('title_en', 500);
    table.string('title_am', 500);
    table.string('title_om', 500);
    table.string('title_so', 500);
    table.integer('display_order').defaultTo(0);
    table.timestamp('created_at').defaultTo(knex.fn.now());
    table.index('week_id');
  });
};

exports.down = async function (knex) {
  await knex.schema.dropTableIfExists('fetal_checklist_items');
  await knex.schema.dropTableIfExists('fetal_development_items');
  await knex.schema.dropTableIfExists('fetal_weekly_content');
};